# Generated by Django 5.0 on 2024-02-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'subcategoria',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('estado', models.BooleanField(default=True)),
                ('id_subcategoria', models.ManyToManyField(null=True, to='categoria.subcategoria')),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
    ]
