# Generated by Django 5.0 on 2024-02-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_alter_categoria_id_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='id_subcategoria',
            field=models.ManyToManyField(related_name='subcategorias', to='categoria.subcategoria', verbose_name='Subcategorías asociadas'),
        ),
    ]
