# Generated by Django 5.0 on 2024-01-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposicion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposicion',
            name='fecha_emision',
            field=models.DateField(),
        ),
    ]
