# Generated by Django 5.0 on 2024-03-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposicion', '0002_alter_disposicion_fecha_emision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emisor',
            name='descripcion',
            field=models.CharField(verbose_name='Emisor'),
        ),
        migrations.AlterField(
            model_name='estadodisposicion',
            name='descripcion',
            field=models.CharField(verbose_name='Nombre de estado de disposición'),
        ),
        migrations.AlterField(
            model_name='tipodisposicionemite',
            name='descripcion',
            field=models.CharField(verbose_name='Disposición'),
        ),
        migrations.AlterField(
            model_name='tipodisposicionfuncion',
            name='descripcion',
            field=models.CharField(verbose_name='Disposición'),
        ),
    ]
