# Generated by Django 5.0 on 2024-01-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='id_permiso',
            field=models.ManyToManyField(to='usuario.permiso', verbose_name='Permiso'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='Usuario'),
        ),
    ]
