# Generated by Django 5.0 on 2024-02-07 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_rol_id_permiso_alter_usuario_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permiso',
            old_name='descripcion',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='descripcion',
            new_name='nombre',
        ),
    ]
