# Generated by Django 5.0 on 2024-02-13 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_rename_descripcion_permiso_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, db_column='id_rol', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.rol'),
        ),
    ]
